# Random Forest Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Final_data.csv')
X = dataset.iloc[:, 1:3].values
y = dataset.iloc[:, 3].values
print(X)
print(y)

[[15.5 'Strong']
 [23.75 'Weak']
 [8.0 'Medium']
 [17.0 'Medium']
 [5.5 'Weak']
 [19.0 'Weak']
 [24.0 'Medium']
 [2.5 'Medium']
 [7.5 'Strong']
 [11.0 'Medium']
 [13.0 'Strong']
 [3.75 'Weak']
 [25.0 'Strong']
 [9.75 'Strong']
 [22.0 'Medium']
 [18.0 'Medium']
 [6.0 'Strong']
 [12.5 'Medium']
 [2.0 'Medium']
 [21.5 'Weak']]
[2158.   1678.15 2316.   2061.3  2207.5  1708.3  1784.7  2575.   2357.9
 2265.7  2156.2  2399.55 1779.8  2336.75 1765.3  2053.5  2414.4  2200.5
 2654.2  1753.7 ]


## Encoding categorical data

### Encoding the Independent Variable

In [3]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [4]:
print(X)

[[0.0 1.0 0.0 15.5]
 [0.0 0.0 1.0 23.75]
 [1.0 0.0 0.0 8.0]
 [1.0 0.0 0.0 17.0]
 [0.0 0.0 1.0 5.5]
 [0.0 0.0 1.0 19.0]
 [1.0 0.0 0.0 24.0]
 [1.0 0.0 0.0 2.5]
 [0.0 1.0 0.0 7.5]
 [1.0 0.0 0.0 11.0]
 [0.0 1.0 0.0 13.0]
 [0.0 0.0 1.0 3.75]
 [0.0 1.0 0.0 25.0]
 [0.0 1.0 0.0 9.75]
 [1.0 0.0 0.0 22.0]
 [1.0 0.0 0.0 18.0]
 [0.0 1.0 0.0 6.0]
 [1.0 0.0 0.0 12.5]
 [1.0 0.0 0.0 2.0]
 [0.0 0.0 1.0 21.5]]


## Training the Random Forest Regression model on the whole dataset

In [5]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X, y)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting a new result

In [7]:
regressor.predict([[0.0,1.0,0.0,14.0]])

array([2160.99])

In [9]:
regressor.predict([[0.0,1.0,0.0,9.0]])

array([2329.515])